"""Packing auxiliary bits into a virtual-table rowid.

A SQLite rowid is a signed 64-bit integer, so a table whose identity needs more
than one value borrows the high bits of a base value (usually an address) for a
payload. That works only because a real address has uniform high bits -- zeros
for userspace, ones for kernel -- so the borrowed bits are redundant and are
regenerated by sign extension on decode.
"""

from .u64 import decode_sql_u64, encode_sql_u64

_U64_MASK = (1 << 64) - 1


def pack_rowid(value: int, payload: int, *, payload_bits: int) -> int:
    """Pack *payload* into the low *payload_bits* of a rowid carrying *value*.

    *value* is an unsigned 64-bit integer, and must be canonical for this payload
    size: its top ``payload_bits + 1`` bits all 0 or all 1, so the bits shifted out
    are recoverable. A non-canonical value raises rather than producing a rowid
    that decodes to a different address.
    """
    payload_limit = 1 << payload_bits
    if not 0 <= payload < payload_limit:
        msg = f"payload {payload} does not fit in {payload_bits} bits (max {payload_limit - 1})"
        raise ValueError(msg)

    canonical_all_ones = (1 << (payload_bits + 1)) - 1
    top_bits = value >> (63 - payload_bits)
    # Also rejects negatives (arithmetic shift keeps them negative) and values
    # >= 2**64, so no separate range checks are needed.
    if top_bits not in (0, canonical_all_ones):
        msg = (
            f"value {value:#x} cannot carry a {payload_bits}-bit payload: it must be an "
            f"unsigned 64-bit integer whose top {payload_bits + 1} bits are all 0 or all 1"
        )
        raise ValueError(msg)

    raw = ((value << payload_bits) | payload) & _U64_MASK
    return encode_sql_u64(raw)


def unpack_rowid(rowid: int, *, payload_bits: int) -> tuple[int, int]:
    """Split a rowid built by ``pack_rowid`` into ``(value, payload)``.

    *value* comes back as an unsigned 64-bit integer, sign-extended from the
    highest bit that still belongs to it.
    """
    raw = decode_sql_u64(rowid)
    payload = raw & ((1 << payload_bits) - 1)
    value = raw >> payload_bits

    value_bits = 64 - payload_bits
    if value >> (value_bits - 1):
        value |= _U64_MASK & ~((1 << value_bits) - 1)
    return value, payload
